FROM php:8.4-apache
RUN docker-php-ext-install pdo pdo_mysql
#ADD ./src /var/www/html

RUN apt update
RUN apt install -y git
RUN git clone https://github.com/DAW2B-DWES-25-26/DWES-25-26-Guillermo-Sobrino-Rodriguez.git /var/www/html

EXPOSE 80

# Este puerto tiene que ser compatible con el del docker compose