FROM php:8.4-apache
RUN docker-php-ext-install pdo pdo_mysql
#ADD ./src /var/www/html

RUN apt update
RUN apt install -y git
RUN git clone https://github.com/guillermosobrino01/Despliegue-Practica-Php /var/www/html
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html


EXPOSE 80

# Este puerto tiene que ser compatible con el del docker compose